### ISSUE TITLE
feat: Update libp2p-bundle to latest version of libp2p

### ISSUE THREAD

**Issue by sahilpohare** [carsonfarmer/libp2p-bundle#3]
# Feature Request
Libp2p was updated 15 hours ago as of writing this with some breaking changes. v0.31.2.
Can we get an update for this?

**Comment by carsonfarmer** [comment]
Ah thanks for the heads up. Yes I should have some time in the next few days to push an update.

**Comment by carsonfarmer** [comment]
Ok, latest release should have those updated.

**Comment by carsonfarmer** [comment]
Also, would be interested to hear what project(s) you are using this library for?
